name: Pylint

on:
  push:
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project:
          - name: analysis
            path: analysis
          - name: backend
            path: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Lint ${{ matrix.project.name }}
        run: |
          set -e

          echo "Linting ${{ matrix.project.name }}"

          python -m venv venv
          source venv/bin/activate

          pip install --upgrade pip
          pip install pylint

          pip install -r "${{ matrix.project.path }}/requirements.txt"

          files=$(git ls-files '${{ matrix.project.path }}/**/*.py')

          if [ -n "$files" ]; then
            pylint --rcfile="${{ matrix.project.path }}/.pylintrc"--fail-under=8.5 $files
          else
            echo "No Python files found in ${{ matrix.project.name }}"
          fi
